### ISSUE TITLE
Remotely moved file outside of sync scope is not removed.

### ISSUE THREAD

**Issue by Uniqen** [skilion/onedrive#341]
In my test configuration the sync_list-file contains 'test' so only the folder `~/OneDrive/test` is synced.

When performing the following steps the file should be removed, imho. L=local computer, R=remote computer
1. L:`touch ~/OneDrive/test/testfile` (File is uploaded).
2. R:`mv ~/OneDrive/test/testfile ~/OneDrive/otherfolder/testfile`. 
3. L: ~/OneDrive/test/testfile should be removed but it is not.

But when running: R: `rm ~/OneDrive/otherfolder/testfile` the file ~/OneDrive/test/testfile on L is removed.
Also tested with #314 with same result.

**Comment by sbocquet** [comment]
Hi !

Strange as it totally works for me with the latest commit from https://github.com/abraunegg/onedrive which is a copy of #314 ...
Moving a file locally outside of the OneDrive scoop delete it.

**Comment by sbocquet** [comment]
Just done the test, and the file is moved...

```
Uploading file Documents/test1.txt... done.
Downloading Documents/Nouveau document texte.txt... done.
Uploading file ./Documents/test.txt... done.
Moving Documents/test1.txt to Documents/Autres/test1.txt
Moving Documents/Autres/test1.txt to Documents/test1.txt
```

Sorry, I cannot reproduce it with the latest commit.

**Comment by Uniqen** [comment]
Maybe I need to be clearer in my description, updated it again. The sync_list-file contains 'test' so only files under test should be synced. As I move the file outside of ~/OneDrive/test (to ~/OneDrive/otherfodler) the file should be removed.

It should not be moved (and isn't in my test so I think you are moving the file inside of your sync scope).

**Comment by sbocquet** [comment]
OK... sorry, didn't go back to the top of the thread.

So you're right. When moving the file outside of the scope but inside OneDrive global scope didn't delete it from the original place... but should? I've got the same here.

**Comment by abraunegg** [comment]
OK .. I do not know how robust the  `sync_list-file` code is at present.

If you are looking at doing a single directory sync do the following at both sides:

```onedrive --synchronize --verbose --single-directory 'test'```

This would sync all files under ~/OneDrive/test/

If a file gets moved out of this dir, it would get deleted on both sides

**Comment by Uniqen** [comment]
When running: `onedrive --monitor --confdir /config --syncdir /onedrive  --single-directory testsync`

I get the error below. Seems to be related to that i'm using a business account according to abraunegg 's comment in #335 :

```app: Syncing changes from selected OneDrive path first before uploading local changes ...
Syncing changes from selected OneDrive path first before uploading local changes ...
onedrive.OneDriveException@src/onedrive.d(539): HTTP request returned status code 501 (Not Implemented)
{
    "error": {
        "code": "notSupported",
        "innerError": {
            "date": "2018-04-22T18:35:05",
            "request-id": "1aa7a95a-a33a-422c-82d6-d2c08040a342"
        },
        "message": "view.delta can only be called on the root."
    }
}
src/onedrive.d:33 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x59128c]
src/onedrive.d:311 std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x5906ab]
src/onedrive.d:114 std.json.JSONValue onedrive.OneDriveApi.viewChangesById(const(char)[], const(char)[], const(char)[]) [0x58f2a1]
src/sync.d:312 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x59a01f]
src/sync.d:207 void sync.SyncEngine.applyDifferencesSingleDirectory(immutable(char)[]) [0x599b20]
src/main.d:307 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x582439]
src/main.d:256 _Dmain [0x581f8c]
```

**Comment by abraunegg** [comment]
Hi,

I am actually in the process of getting this fixed as I came across this a few days ago (https://github.com/abraunegg/onedrive/commit/fedaedacd777548b3651071519b61a8544e03ade) however this fix broke things. I have a partially working fix locally at the moment, needs a bit more work & then testing against ~30 odd sanity checks I use to test the functionality of the client.

Best regards,

Alex

**Comment by abraunegg** [comment]
@Uniqen 

I have published the full fix for `view.delta can only be called on the root` in dff245d29bf09c979d5bc40e82b852b48c957ac5 after performing validation and testing on this change.

**Comment by Uniqen** [comment]
@abraunegg 
Thank you, dff245d resolved `the view.delta can only be called on the root.` for me.

Although the original issue is still not working when using: `onedrive --monitor --confdir /config --syncdir /onedrive --resync --verbose --single-directory testsync` instead of the sync_list-file.

**Comment by abraunegg** [comment]
when using the `--single-directory` flag, this only looks at changes that occur for this path.

If we are moving a file as follows:

```testdir/1.txt -> otherFolder/1.txt```

and we are syncing `testdir`, OneDrive responds with the following JSON for the move as a change:

```
Found Change: {"@odata.etag":"\"{<redacted>},1\"","@odata.type":"#microsoft.graph.driveItem","eTag":"\"{<redacted>},1\"","fileSystemInfo":{"createdDateTime":"2018-04-23T08:44:07Z","lastModifiedDateTime":"2018-04-23T08:44:07Z"},"folder":{"childCount":1},"id":"<redacted>","name":"otherdir","parentReference":{"driveId":"<redacted>","driveType":"business","id":"<redacted>","path":"\/drives\/<redacted>\/root:"}}
CLIENT CHANGE DISCARDED
Found Change: {"@odata.etag":"\"{<redacted>},3\"","@odata.type":"#microsoft.graph.driveItem","eTag":"\"{<redacted>},3\"","file":{"hashes":{"quickXorHash":"YZgDGcwQhjmQwQxhlgMZzBAGBQA="},"mimeType":"text\/plain"},"fileSystemInfo":{"createdDateTime":"2018-04-23T08:43:50Z","lastModifiedDateTime":"2018-04-23T08:43:00Z"},"id":"<redacted>","name":"1.txt","parentReference":{"driveId":"<redacted>","driveType":"business","id":"<redacted>","path":"\/drives\/<redacted>\/root:\/otherdir"}}
CLIENT CHANGE DISCARDED
```
The reason for this is simply what we are only looking at changes attributed to `testdir` but there is nothing in the JSON response that indicates that this is a move action change.

This being said, if I make the file move on the local system, and tell onedrive client to use my local system as 'source of truth' via the `--local-first` flag the file (moved locally is already in the correct directory) is deleted from the 'testdir' inside OneDrive online.

In your top post, you have 2 systems - L & R. I would use `--local-first` on one side and have this as the 'source of truth' and R not use `--local-first` so that R uses OneDrive as it's 'source of truth'

Having a file left behind on the local system after it's moved to an unsynced directory inside OneDrive is a quirk side effect of using the '--single-directory' flag and it makes sense why your seeing this.

I will put it on the whiteboard as a 'quirk' - add it to the readme, and look at in the future how maybe the '--single-directory' handling of moves of synced objects can be better performed.

**Comment by Uniqen** [comment]
Ok, thank you for looking into this. Do you want me to close this issue? 

As a workaround I will first move the files outside of OneDrive entirely and wait for monitor sync and then move the files into the new folder. This seems to be working.

**Comment by abraunegg** [comment]
Leave this issue open so I can report back when I have a solution. I have some idea's on how this can be solved - need to try them.

**Comment by abraunegg** [comment]
I have posted a fix for this edge case issue when using the `--single-directory` switch & moving a file on OneDrive to a new location. Commit ccd4dfbaf722d732ef273c5e39cd4aed90ea2dae should fix this as I have tested this locally and no issue.

**Comment by Uniqen** [comment]
@abraunegg 
Just built a docker container including latest abraunegg/onedrive (90dec8d) to verify this. But at start up i got the following assertion error which looks like it is related to your changes in ccd4dfb.

```
Syncing changes from selected OneDrive path first before uploading local changes ...
core.exception.AssertError@src/itemdb.d(293): Assertion failure
----------------
??:? _d_assertp [0x5ace69]
src/itemdb.d:293 immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x57f550]
src/sync.d:377 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x59b6c1]
src/sync.d:212 void sync.SyncEngine.applyDifferencesSingleDirectory(immutable(char)[]) [0x59ac74]
src/main.d:320 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x5835f9]
src/main.d:219 _Dmain [0x583007]
```

**Comment by abraunegg** [comment]
Can you post the full log / full command line used?

I am not getting an assertion when I tested all options .. The only way it could asset there would be if:
```
driveId, item["id"].str
```
have no entry. 

driveId gets set as a global variable upon initialisation, and the items id is pulled in from the previous query:
```
oneDriveMovedNotDeleted = onedrive.getPathDetailsById(item["id"].str);
```

**Comment by Uniqen** [comment]
Running: `onedrive --monitor --confdir /config --syncdir /onedrive --resync --verbose --single-directory testsync` although i get the same error without --resync (only later). No /config/skip_file or /config/sync_list is used.

```
2018-May-01 20:19:44.2435406 Loading config ...
2018-May-01 20:19:44.2454676 Using Config Dir: /config
2018-May-01 20:19:44.2477294 No config file found, using defaults
2018-May-01 20:19:44.2494873 Deleting the saved status ...
2018-May-01 20:19:44.2524335 Initializing the OneDrive API ...
2018-May-01 20:19:44.4159283 Opening the item database ...
2018-May-01 20:19:44.4389964 All operations will be performed in: /onedrive
2018-May-01 20:19:44.441088 Initializing the Synchronization Engine ...
2018-May-01 20:19:45.3899388 Account Type: business
2018-May-01 20:19:45.3937872 Default Drive ID: b!KVj6Ovfc0EKN8K6vGUQVx-IREDACTEDNIqH
2018-May-01 20:19:45.3966302 Default Root ID: 01C3XREDACTEDWSELRRZ
2018-May-01 20:19:45.399595 Remaining Free Space: 1099019950722
2018-May-01 20:19:45.4018816 Fetching details for OneDrive Root
2018-May-01 20:19:45.7420382 OneDrive Root does not exist in the database. We need to add it.
2018-May-01 20:19:45.7564613 Added OneDrive Root to the local database
2018-May-01 20:19:45.7585934 Syncing changes from this selected path: testsync
2018-May-01 20:19:45.7599041 Syncing changes from selected OneDrive path first before uploading local changes ...
2018-May-01 20:19:46.0551831 Getting path details from OneDrive ...
2018-May-01 20:19:46.3321192 Applying changes of Path ID: 01C3XPREDACTEDL5C2AUE4
```

**Comment by abraunegg** [comment]
That log snippet doesn't show me the error. '01C3XPREDACTEDL5C2AUE4' would correlate to the 'testsync' directory.

Can you show me the full log where you 'get the error later' when not using --resync ?

1. Delete the items database file
2. Run the application not in monitor mode: `onedrive --confdir /config --syncdir /onedrive --verbose --single-directory 'testsync'`

Also note the quotes around the testsync directory.

**Comment by Uniqen** [comment]
Using: `onedrive --synchronize --confdir /config --syncdir /onedrive --verbose --single-directory 'testsync'`

This is the entire output:
```
Using Config Dir: /config
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /onedrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!KVj6Ovfc0EKN8K6vGUQVx-IRlyOyXHZGgdR5E3yFCyFSjXP2sCocTrvA9zAONIqH
Default Root ID: 01C3XPASV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1099019950722
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from this selected path: testsync
Syncing changes from selected OneDrive path first before uploading local changes ...
Getting path details from OneDrive ...
Applying changes of Path ID: 01C3XPASUC5P6EVEE5XRH3CPCLL5C2AUE4
core.exception.AssertError@src/itemdb.d(293): Assertion failure
----------------
??:? _d_assertp [0x5ace69]
src/itemdb.d:293 immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x57f550]
src/sync.d:377 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x59b6c1]
src/sync.d:212 void sync.SyncEngine.applyDifferencesSingleDirectory(immutable(char)[]) [0x59ac74]
src/main.d:320 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x5835f9]
src/main.d:219 _Dmain [0x583007]
```

**Comment by abraunegg** [comment]
I am struggling to replicate your 'crash'

The exact steps I am taking are:

1. Copy data locally to desired local path
2. Sync using `onedrive --synchronize --verbose --single-directory '<dirname>'`
3. Validate files & folders are on OneDrive & reflects the local state
4. Select a file or folder from the synced path & move to OneDrive Root or another folder other than the one I am syncing in step 2 above
5. Sync using `onedrive --synchronize --verbose --single-directory '<dirname>'`

Each time I sync after performing those tasks, the item I have moved in OneDrive is deleted from the 'local path' as expected:

```
Loading config ...
Using Config Dir: /root/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 1096322795968
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from this selected path: 564dfa8a-bd52-969a-f4c6-38488860d952
Syncing changes from selected OneDrive path first before uploading local changes ...
Getting path details from OneDrive ...
Applying changes of Path ID: 01D6JQORTYF7KFSRRMY5BJWCB4PH4CTQDI
Deleting item 564dfa8a-bd52-969a-f4c6-38488860d952/pictures/eakbas/week02-03-Combinational_Logic-v1.pptx
Deleting item 564dfa8a-bd52-969a-f4c6-38488860d952/pictures/eakbas
Uploading differences of 564dfa8a-bd52-969a-f4c6-38488860d952
Processing 564dfa8a-bd52-969a-f4c6-38488860d952
The directory has not changed
Processing pictures
The directory has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing campover.pdf
The file has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing SMPP
The directory has not changed
Processing SMPP-IF-SPEC_v3_3-24858.pdf
The file has not changed
Processing SMPP_v3_4_Issue1_2-24857.pdf
The file has not changed
Uploading new items of 564dfa8a-bd52-969a-f4c6-38488860d952
```

What are your exact reproduction steps here that is causing the crash?

**Comment by Uniqen** [comment]
I'm sorry if I was unclear. Since ccd4dfb I get the assertion error immediately when starting onedrive using single-directory, no move or anything is performed.

I will try to reproduce the error without running in a docker container tomorrow.

**Comment by abraunegg** [comment]
OK ... that is weird.

Please can you ensure that you remove the items database file as well when attempting to perform the test.

**Comment by Uniqen** [comment]
I removed the items database file and tested with a new empty folder with same result.

Also tested on my ubuntu server with the same result (no docker involved). 

1. Could it be related to that I'm using Account Type: business?
2. Are there any debug logging that would facilitate solving the issue?

This is the entire output when running on the server:
```
./onedrive --synchronize --confdir ~/onedrive/config --syncdir ~/onedrive/data --verbose --single-directory 'testsingle'
Loading config ...
Using Config Dir: /root/onedrive/config
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/onedrive/data
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 1099019950303
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from this selected path: testsingle
Syncing changes from selected OneDrive path first before uploading local changes ...
Getting path details from OneDrive ...
Applying changes of Path ID: <redacted>
core.exception.AssertError@src/itemdb.d(295): Assertion failure
----------------
??:? _d_assertp [0xace9ce79]
??:? immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0xace6fa60]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0xace8bc9e]
??:? void sync.SyncEngine.applyDifferencesSingleDirectory(immutable(char)[]) [0xace8b1a8]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0xace73b61]
??:? _Dmain [0xace7356f]
```

**Comment by abraunegg** [comment]
If we can organise to do a WebEx on the system so I can make some debugging edits realtime that would be great. I am using a 'business' account to test, so that is not the issue.

**Comment by abraunegg** [comment]
@Uniqen 
I have added some additional checks into the code -  commit 9520fe7 - that should 'hopefully' take care of the crash your seeing. Can you please help validate?

**Comment by Uniqen** [comment]
\o/ 9520fe7 resolved the assertion error I was getting. I have also verified that the original issue is resolved. 

Closing this as it is resolved in #314 (or using abraunegg/onedrive). Thank you @abraunegg
