### ISSUE TITLE
Deletes all my files when SIGINT

### ISSUE THREAD

**Issue by Modelmat** [skilion/onedrive#412]
When using onedrive, sometimes I have hit Ctrl + C to stop it temporarily. This results in when I start running it again that it deletes all the files I have not synced to the local directory.

Is it possible to handle the SIGINT and set a partial sync state (ie. download the rest of the files)?

**Comment by abraunegg** [comment]
This is a known issue with the skilion codebase but resolved in my branch.

**Comment by Modelmat** [comment]
As a matter of fact it does the same thing with your branch. Os no, it's not resolved.

**Comment by abraunegg** [comment]
If you can open a case against my branch and provide verbose logs & exact replication proceedures I can provide a fix. The skilion codebase contains many defects that have not been fixed

**Comment by abraunegg** [comment]
@Modelmat 
You are missing important diagnostic information such as:
* onedrive application version - output of: `onedrive --version`
* verbose log showing the error

**Comment by Modelmat** [comment]
I use verbose, all it gives is "deleting file ..."
`onedrive v2.1.2-5-g53cbc8f` is the version.

**Comment by abraunegg** [comment]
@Modelmat
Then close this case and open it on my branch so that the 'issue' is tagged against the right version of code - not the 'skilion' branch
